In [50]:
import sys
import numpy as np
import pandas as pd
import statsmodels.api as sm
import os
import warnings
import folium
import branca

warnings.filterwarnings("ignore")

In [51]:
df_filled_23 = pd.read_pickle(r'D:\capstone_F24\data\Cleaned_data\df_filled_23.pkl')

In [52]:
df_filled_23

timestamp,2023-02-01 00:00:00,2023-02-01 01:00:00,2023-02-01 02:00:00,2023-02-01 03:00:00,2023-02-01 04:00:00,2023-02-01 05:00:00,2023-02-01 06:00:00,2023-02-01 07:00:00,2023-02-01 08:00:00,2023-02-01 09:00:00,...,2023-12-31 14:00:00,2023-12-31 15:00:00,2023-12-31 16:00:00,2023-12-31 17:00:00,2023-12-31 18:00:00,2023-12-31 19:00:00,2023-12-31 20:00:00,2023-12-31 21:00:00,2023-12-31 22:00:00,2023-12-31 23:00:00
station_complex_id,,,,,,,,,,,,,,,,,,,,,
1,27.0,16.0,15.0,16.0,47.0,227.0,654.0,1528.0,2208.0,1020.0,...,383.0,334.0,334.0,357.0,406.0,307.0,335.0,319.0,234.0,63.0
10,167.0,46.0,26.0,10.0,8.0,25.0,84.0,222.0,490.0,399.0,...,1.0,4.0,3.0,1.0,4.0,2.0,5.0,3.0,5.0,2.0
100,13.0,2.0,1.0,2.0,6.0,15.0,75.0,141.0,281.0,161.0,...,81.0,66.0,60.0,50.0,71.0,74.0,101.0,84.0,54.0,26.0
101,59.0,30.0,13.0,6.0,18.0,61.0,230.0,635.0,1223.0,765.0,...,353.0,364.0,376.0,364.0,290.0,318.0,302.0,270.0,217.0,107.0
118,94.0,25.0,15.0,3.0,4.0,9.0,49.0,95.0,188.0,114.0,...,212.0,231.0,249.0,236.0,292.0,286.0,309.0,320.0,326.0,148.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,15.0,3.0,6.0,13.0,39.0,87.0,233.0,566.0,768.0,433.0,...,193.0,197.0,147.0,143.0,182.0,191.0,164.0,141.0,114.0,55.0
96,13.0,6.0,5.0,8.0,24.0,72.0,193.0,421.0,621.0,364.0,...,175.0,157.0,121.0,136.0,153.0,214.0,159.0,139.0,105.0,51.0
97,31.0,14.0,19.0,22.0,37.0,118.0,290.0,871.0,1367.0,837.0,...,337.0,303.0,282.0,301.0,289.0,341.0,265.0,338.0,207.0,122.0
98,31.0,5.0,10.0,4.0,26.0,59.0,160.0,310.0,429.0,293.0,...,173.0,186.0,213.0,182.0,184.0,152.0,149.0,119.0,102.0,39.0
99,14.0,1.0,4.0,1.0,8.0,44.0,116.0,256.0,384.0,225.0,...,104.0,115.0,106.0,99.0,88.0,92.0,79.0,92.0,51.0,27.0

In [53]:
time_cols = df_filled_23.columns

In [54]:
df_23_pred = pd.read_pickle('df_23_pred.pkl')

In [55]:
df_23_pred

,station_complex_id,predicted_ridership_2023,predicted_timestamps
0,1,"[44.99774297489933, 20.8311131963189, 14.01589...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
1,10,"[0.6377865430228253, -0.43231439031105057, -0....","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
2,100,"[19.375849590191244, 9.485234104879147, 6.0255...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
3,101,"[65.80243855395817, 33.77050425148411, 19.5834...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
4,118,"[69.09470590092661, 31.96459776749566, 17.1971...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
...,...,...,...
356,95,"[33.65158783570899, 17.02208648432609, 15.6516...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
357,96,"[40.19121795211857, 23.248138439804983, 15.658...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
358,97,"[50.402836806840995, 27.46710833259318, 30.456...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
359,98,"[22.130989560671487, 9.10391059220381, 6.10345...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."
360,99,"[13.454066961828353, 6.565974289944839, 3.2425...","[2023-01-01 00:00:00, 2023-01-01 01:00:00, 202..."

In [56]:
df_23_pred = df_23_pred.drop(columns='predicted_timestamps')

In [57]:
df_23_pred.columns

Index(['station_complex_id', 'predicted_ridership_2023'], dtype='object')

In [58]:
list_size = df_23_pred[df_23_pred['station_complex_id']=='1']['predicted_ridership_2023'].values.tolist()

In [59]:
len(list_size[0])

8016

In [60]:
# Set index to station_complex_id
df_23_pred = df_23_pred.set_index("station_complex_id")

# Expand the lists in predicted_ridership_2023 into new columns
expanded_23_pred = pd.DataFrame(df_23_pred["predicted_ridership_2023"].tolist(), 
                           index=df_23_pred.index, 
                           columns=time_cols)

expanded_23_pred

timestamp,2023-02-01 00:00:00,2023-02-01 01:00:00,2023-02-01 02:00:00,2023-02-01 03:00:00,2023-02-01 04:00:00,2023-02-01 05:00:00,2023-02-01 06:00:00,2023-02-01 07:00:00,2023-02-01 08:00:00,2023-02-01 09:00:00,...,2023-12-31 14:00:00,2023-12-31 15:00:00,2023-12-31 16:00:00,2023-12-31 17:00:00,2023-12-31 18:00:00,2023-12-31 19:00:00,2023-12-31 20:00:00,2023-12-31 21:00:00,2023-12-31 22:00:00,2023-12-31 23:00:00
station_complex_id,,,,,,,,,,,,,,,,,,,,,
1,44.997743,20.831113,14.015898,17.815409,57.416064,185.871864,434.907199,839.610537,1091.586632,749.823880,...,1905.625302,1826.121774,1820.936700,1860.737864,1503.311632,1022.321055,772.504898,592.839719,526.970325,283.512363
10,0.637787,-0.432314,-0.727984,-0.837661,-0.827902,-0.736454,-0.336859,0.408229,1.845614,2.650850,...,-0.668272,-0.588526,-0.440530,-0.282214,-0.439614,-0.597290,-0.668959,-0.615787,-0.567656,-0.723216
100,19.375850,9.485234,6.025507,4.412437,9.351398,15.671728,38.628597,70.577131,112.912515,94.734594,...,1440.656373,1566.617181,1589.506283,1607.411810,1510.051114,1136.994000,842.252609,556.448777,486.363736,375.855151
101,65.802439,33.770504,19.583496,13.533800,19.851599,52.289790,124.091671,261.166142,435.244765,327.458649,...,799.036060,931.341885,1067.845269,1095.022656,972.248272,749.394115,578.943325,425.466191,362.705663,283.500614
118,69.094706,31.964598,17.197161,9.281847,8.067009,9.062392,23.617992,63.080299,85.784517,87.539774,...,482.319020,675.303655,667.620687,697.952844,675.595294,626.022853,563.018533,520.031326,468.548587,330.154780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,33.651588,17.022086,15.651613,17.484488,52.051402,125.872212,260.295779,490.976410,649.441211,557.557151,...,13014.522558,13202.292374,13065.054491,12790.290553,10497.305016,7655.242504,4930.146792,3378.218525,2710.542999,1735.530425
96,40.191218,23.248138,15.658215,18.239913,45.443364,99.878363,215.025678,388.856878,556.847149,506.690011,...,106783.144820,106207.815447,103016.018004,98734.059152,83170.135768,57516.778245,39651.962737,30948.198585,27733.714702,17191.471375
97,50.402837,27.467108,30.456254,21.037095,39.479223,79.378789,174.828960,334.269557,485.523609,441.372172,...,556.389733,574.132876,576.991378,600.644661,509.135556,353.403063,245.612839,184.271449,174.559387,122.056086
98,22.130990,9.103911,6.103457,6.337204,15.613535,28.677702,70.903629,120.816272,169.618078,147.678173,...,59.651666,65.588141,78.728260,68.034038,47.317115,36.662910,27.211469,14.803919,11.173865,8.615516
99,13.454067,6.565974,3.242544,3.171757,4.518395,16.844445,49.827878,86.619874,128.121672,112.202872,...,45.628418,43.990318,51.496773,49.766238,38.367767,27.690891,20.695496,15.327250,11.542998,8.807679

In [61]:
expanded_23_pred.to_pickle(r'D:\capstone_F24\data\Cleaned_data\expanded_23_pred.pkl')

In [62]:
# Reset index to include station_complex_id as a column
preds_long = expanded_23_pred.reset_index().melt(
    id_vars=["station_complex_id"],  # Columns to keep as identifiers
    var_name="timestamp",           # Name for the 'wide' columns (timestamps)
    value_name="ridership"          # Name for the values in those columns
)

# Convert the timestamp column to a proper datetime type if necessary
preds_long["timestamp"] = pd.to_datetime(preds_long["timestamp"])

preds_long

        station_complex_id           timestamp     ridership
0                        1 2023-02-01 00:00:00     44.997743
1                       10 2023-02-01 00:00:00      0.637787
2                      100 2023-02-01 00:00:00     19.375850
3                      101 2023-02-01 00:00:00     65.802439
4                      118 2023-02-01 00:00:00     69.094706
...                    ...                 ...           ...
2893771                 95 2023-12-31 23:00:00   1735.530425
2893772                 96 2023-12-31 23:00:00  17191.471375
2893773                 97 2023-12-31 23:00:00    122.056086
2893774                 98 2023-12-31 23:00:00      8.615516
2893775                 99 2023-12-31 23:00:00      8.807679

[2893776 rows x 3 columns]

In [63]:
# Reset index to include station_complex_id as a column
actual_long = df_filled_23.reset_index().melt(
    id_vars=["station_complex_id"],  # Columns to keep as identifiers
    var_name="timestamp",           # Name for the 'wide' columns (timestamps)
    value_name="ridership"          # Name for the values in those columns
)

# Convert the timestamp column to a proper datetime type if necessary
actual_long["timestamp"] = pd.to_datetime(actual_long["timestamp"])

actual_long

        station_complex_id           timestamp  ridership
0                        1 2023-02-01 00:00:00       27.0
1                       10 2023-02-01 00:00:00      167.0
2                      100 2023-02-01 00:00:00       13.0
3                      101 2023-02-01 00:00:00       59.0
4                      118 2023-02-01 00:00:00       94.0
...                    ...                 ...        ...
2893771                 95 2023-12-31 23:00:00       55.0
2893772                 96 2023-12-31 23:00:00       51.0
2893773                 97 2023-12-31 23:00:00      122.0
2893774                 98 2023-12-31 23:00:00       39.0
2893775                 99 2023-12-31 23:00:00       27.0

[2893776 rows x 3 columns]

In [64]:
# Rename the 'ridership' column in preds_long to 'predicted'
preds_long = preds_long.rename(columns={"ridership": "predicted"})

# Rename the 'ridership' column in actual_long to 'actual'
actual_long = actual_long.rename(columns={"ridership": "actual"})

# Merge preds_long with actual_long on 'station_complex_id' and 'timestamp'
pred_vs_actual = actual_long.merge(
    preds_long[["station_complex_id", "timestamp", "predicted"]],  # Select relevant columns from preds_long
    on=["station_complex_id", "timestamp"],                       # Merge on these columns
    how="inner"                                                   # Use inner join to keep only matching rows
)

pred_vs_actual

        station_complex_id           timestamp  actual     predicted
0                        1 2023-02-01 00:00:00    27.0     44.997743
1                       10 2023-02-01 00:00:00   167.0      0.637787
2                      100 2023-02-01 00:00:00    13.0     19.375850
3                      101 2023-02-01 00:00:00    59.0     65.802439
4                      118 2023-02-01 00:00:00    94.0     69.094706
...                    ...                 ...     ...           ...
2893771                 95 2023-12-31 23:00:00    55.0   1735.530425
2893772                 96 2023-12-31 23:00:00    51.0  17191.471375
2893773                 97 2023-12-31 23:00:00   122.0    122.056086
2893774                 98 2023-12-31 23:00:00    39.0      8.615516
2893775                 99 2023-12-31 23:00:00    27.0      8.807679

[2893776 rows x 4 columns]

In [65]:
df_filled_22 = pd.read_pickle(r'D:\capstone_F24\data\Cleaned_data\df_filled_22.pkl')

In [66]:
df_filled_22

timestamp,2022-02-01 00:00:00,2022-02-01 01:00:00,2022-02-01 02:00:00,2022-02-01 03:00:00,2022-02-01 04:00:00,2022-02-01 05:00:00,2022-02-01 06:00:00,2022-02-01 07:00:00,2022-02-01 08:00:00,2022-02-01 09:00:00,...,2022-12-31 14:00:00,2022-12-31 15:00:00,2022-12-31 16:00:00,2022-12-31 17:00:00,2022-12-31 18:00:00,2022-12-31 19:00:00,2022-12-31 20:00:00,2022-12-31 21:00:00,2022-12-31 22:00:00,2022-12-31 23:00:00
station_complex_id,,,,,,,,,,,,,,,,,,,,,
1,17.0,5.0,6.0,12.0,44.0,143.0,405.0,735.0,950.0,512.0,...,426.0,402.0,304.0,338.0,322.0,350.0,309.0,293.0,168.0,75.0
10,100.0,24.0,7.0,8.0,8.0,14.0,43.0,98.0,175.0,182.0,...,3.0,4.0,4.0,4.0,3.0,4.0,5.0,8.0,5.0,2.0
100,10.0,3.0,0.0,3.0,5.0,17.0,46.0,68.0,106.0,66.0,...,68.0,69.0,69.0,55.0,58.0,61.0,67.0,52.0,56.0,25.0
101,26.0,10.0,9.0,3.0,20.0,49.0,124.0,245.0,394.0,247.0,...,286.0,316.0,332.0,269.0,239.0,246.0,239.0,209.0,179.0,104.0
118,21.0,11.0,9.0,3.0,1.0,9.0,14.0,61.0,75.0,54.0,...,249.0,279.0,245.0,245.0,287.0,273.0,278.0,281.0,245.0,115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,6.0,2.0,5.0,6.0,24.0,85.0,135.0,296.0,298.0,196.0,...,227.0,147.0,160.0,143.0,172.0,183.0,170.0,151.0,116.0,62.0
96,11.0,4.0,4.0,7.0,15.0,58.0,113.0,214.0,244.0,169.0,...,194.0,153.0,112.0,128.0,137.0,175.0,181.0,153.0,128.0,61.0
97,13.0,12.0,8.0,10.0,39.0,91.0,229.0,357.0,472.0,317.0,...,276.0,247.0,231.0,198.0,261.0,234.0,314.0,243.0,180.0,83.0
98,18.0,8.0,3.0,2.0,14.0,46.0,127.0,170.0,223.0,178.0,...,189.0,196.0,188.0,141.0,118.0,156.0,121.0,84.0,85.0,39.0
99,9.0,2.0,1.0,0.0,2.0,30.0,60.0,105.0,155.0,123.0,...,101.0,82.0,77.0,68.0,80.0,64.0,73.0,64.0,49.0,24.0

In [67]:
# Reset index to include station_complex_id as a column
actual_22_long = df_filled_22.reset_index().melt(
    id_vars=["station_complex_id"],  # Columns to keep as identifiers
    var_name="timestamp",           # Name for the 'wide' columns (timestamps)
    value_name="ridership"          # Name for the values in those columns
)

# Convert the timestamp column to a proper datetime type if necessary
actual_22_long["timestamp"] = pd.to_datetime(actual_22_long["timestamp"])

actual_22_long

        station_complex_id           timestamp  ridership
0                        1 2022-02-01 00:00:00       17.0
1                       10 2022-02-01 00:00:00      100.0
2                      100 2022-02-01 00:00:00       10.0
3                      101 2022-02-01 00:00:00       26.0
4                      118 2022-02-01 00:00:00       21.0
...                    ...                 ...        ...
2893771                 95 2022-12-31 23:00:00       62.0
2893772                 96 2022-12-31 23:00:00       61.0
2893773                 97 2022-12-31 23:00:00       83.0
2893774                 98 2022-12-31 23:00:00       39.0
2893775                 99 2022-12-31 23:00:00       24.0

[2893776 rows x 3 columns]

In [68]:
# Rename the 'ridership' column in actual_long to 'actual'
pred_vs_actual = pred_vs_actual.rename(columns={"actual": "actual_23", "predicted":"pred_23"})

pred_vs_actual

        station_complex_id           timestamp  actual_23       pred_23
0                        1 2023-02-01 00:00:00       27.0     44.997743
1                       10 2023-02-01 00:00:00      167.0      0.637787
2                      100 2023-02-01 00:00:00       13.0     19.375850
3                      101 2023-02-01 00:00:00       59.0     65.802439
4                      118 2023-02-01 00:00:00       94.0     69.094706
...                    ...                 ...        ...           ...
2893771                 95 2023-12-31 23:00:00       55.0   1735.530425
2893772                 96 2023-12-31 23:00:00       51.0  17191.471375
2893773                 97 2023-12-31 23:00:00      122.0    122.056086
2893774                 98 2023-12-31 23:00:00       39.0      8.615516
2893775                 99 2023-12-31 23:00:00       27.0      8.807679

[2893776 rows x 4 columns]

In [69]:
df_station_info = pd.read_csv(r"D:\capstone_F24\data\MTA_Subway_Stations_20241002.csv")

In [70]:
df_station_info

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
0,R01,1,1,BMT,Astoria,Astoria-Ditmars Blvd,Q,False,N W,Elevated,40.775036,-73.912034,Last Stop,Manhattan,0,0,0,NaN,POINT (-73.912034 40.775036)
1,R03,2,2,BMT,Astoria,Astoria Blvd,Q,False,N W,Elevated,40.770258,-73.917843,Astoria,Manhattan,1,1,1,NaN,POINT (-73.917843 40.770258)
2,R04,3,3,BMT,Astoria,30 Av,Q,False,N W,Elevated,40.766779,-73.921479,Astoria,Manhattan,0,0,0,NaN,POINT (-73.921479 40.766779)
3,R05,4,4,BMT,Astoria,Broadway,Q,False,N W,Elevated,40.761820,-73.925508,Astoria,Manhattan,0,0,0,NaN,POINT (-73.925508 40.76182)
4,R06,5,5,BMT,Astoria,36 Av,Q,False,N W,Elevated,40.756804,-73.929575,Astoria,Manhattan,0,0,0,NaN,POINT (-73.929575 40.756804)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,S15,517,517,SIR,Staten Island,Prince's Bay,SI,False,SIR,Open Cut,40.525507,-74.200064,Ferry,South Shore,0,0,0,NaN,POINT (-74.200064 40.525507)
492,S14,518,518,SIR,Staten Island,Pleasant Plains,SI,False,SIR,Embankment,40.522410,-74.217847,Ferry,South Shore,0,0,0,NaN,POINT (-74.217847 40.52241)
493,S13,519,519,SIR,Staten Island,Richmond Valley,SI,False,SIR,Open Cut,40.519631,-74.229141,Ferry,Tottenville,0,0,0,NaN,POINT (-74.229141 40.519631)
494,S09,522,522,SIR,Staten Island,Tottenville,SI,False,SIR,At Grade,40.512764,-74.251961,Ferry,Last Stop,1,1,1,NaN,POINT (-74.251961 40.512764)
495,S11,523,523,SIR,Staten Island,Arthur Kill,SI,False,SIR,At Grade,40.516578,-74.242096,Ferry,Tottenville,1,1,1,NaN,POINT (-74.242096 40.516578)

In [71]:
df_station_info['Daytime Routes'].unique()

array(['N W', 'N R W', 'N Q R W', 'R W', 'N Q', 'R', 'B Q R', 'D N R',
       'N R', 'B Q', 'B Q S', 'Q', 'F Q', 'D F N Q', 'D', 'N', 'J Z', 'J',
       'M J Z', 'M J', 'M', 'L', 'S', 'A', 'A C', 'C', 'B D', 'C B',
       'A C B D', 'C E', 'A C E', 'B D F M', 'E', 'A C F', 'A C G', 'A S',
       'F', 'F M', 'F G', 'E F', 'E F M R', 'M R', 'E M R', 'E M',
       'E B D', 'E J Z', 'G', '1', '1 2 3', '2 3', '2 3 4 5', '3', '3 4',
       '2 5', '6', '4', '4 5', '4 5 6', '2', '5', '7', 'SIR'],
      dtype=object)

In [72]:
# Cast Complex ID to string in df_station_info
df_station_info['Complex ID'] = df_station_info['Complex ID'].astype(str)

# Remove duplicates in df_station_info based on Complex ID
df_station_info_unique = df_station_info.drop_duplicates(subset=['Complex ID'])

# Select relevant columns from df_station_info
station_info_cols = ['Complex ID', 'Stop Name', 'Borough', 'Daytime Routes', 
                     'Structure', 'GTFS Latitude', 'GTFS Longitude']
df_station_info_selected = df_station_info_unique[station_info_cols]

# Perform the merge
merged_df = pred_vs_actual.merge(
    df_station_info_selected, 
    left_on='station_complex_id', 
    right_on='Complex ID', 
    how='left'
)

# Drop duplicate 'Complex ID' column if desired
merged_df = merged_df.drop(columns=['Complex ID'])

merged_df

,station_complex_id,timestamp,actual_23,pred_23,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude
0,1,2023-02-01 00:00:00,27.0,44.997743,Astoria-Ditmars Blvd,Q,N W,Elevated,40.775036,-73.912034
1,10,2023-02-01 00:00:00,167.0,0.637787,49 St,M,N R W,Subway,40.759901,-73.984139
2,100,2023-02-01 00:00:00,13.0,19.375850,Hewes St,Bk,M J,Elevated,40.706870,-73.953431
3,101,2023-02-01 00:00:00,59.0,65.802439,Marcy Av,Bk,M J Z,Elevated,40.708359,-73.957757
4,118,2023-02-01 00:00:00,94.0,69.094706,3 Av,M,L,Subway,40.732849,-73.986122
...,...,...,...,...,...,...,...,...,...,...
2893771,95,2023-12-31 23:00:00,55.0,1735.530425,Gates Av,Bk,J Z,Elevated,40.689630,-73.922270
2893772,96,2023-12-31 23:00:00,51.0,17191.471375,Kosciuszko St,Bk,J,Elevated,40.693342,-73.928814
2893773,97,2023-12-31 23:00:00,122.0,122.056086,Myrtle Av,Bk,M J Z,Elevated,40.697207,-73.935657
2893774,98,2023-12-31 23:00:00,39.0,8.615516,Flushing Av,Bk,M J,Elevated,40.700260,-73.941126
2893775,99,2023-12-31 23:00:00,27.0,8.807679,Lorimer St,Bk,M J,Elevated,40.703869,-73.947408

In [73]:
# Rename 'GTFS Latitude' and 'GTFS Longitude' columns to 'lat' and 'long' respectively
merged_df.rename(columns={'GTFS Latitude': 'lat', 'GTFS Longitude': 'long', 'Stop Name': 'stop_name', 'Borough': 'borough','Structure': 'structure'}, inplace=True)

# Create proxy variable 'is_weekend' which determines if the timestamp is a weekend (1 for weekend, 0 for weekday)
merged_df['timestamp'] = pd.to_datetime(merged_df['timestamp'])  # Ensure timestamp is in datetime format
merged_df['is_weekend'] = merged_df['timestamp'].dt.weekday >= 5  # 5 and 6 represent Saturday and Sunday
merged_df['is_weekend'] = merged_df['is_weekend'].astype(int)  # Convert boolean to integer (1 for weekend, 0 for weekday)

# Create proxy variable 'day_of_week' which gets the day of the week as an integer (0=Monday, 6=Sunday)
merged_df['day_of_week'] = merged_df['timestamp'].dt.weekday

# Refactor 'Daytime Routes' column into a new column 'routes' which is a list of elements split by space
merged_df['routes'] = merged_df['Daytime Routes'].str.split()

# Add new column 'num_lines_serviced' which is the length of each list in the 'routes' column
merged_df['num_lines_serviced'] = merged_df['routes'].apply(len)

# Drop the 'Daytime Routes' column
merged_df.drop(columns=['Daytime Routes'], inplace=True)

In [74]:
merged_df

,station_complex_id,timestamp,actual_23,pred_23,stop_name,borough,structure,lat,long,is_weekend,day_of_week,routes,num_lines_serviced
0,1,2023-02-01 00:00:00,27.0,44.997743,Astoria-Ditmars Blvd,Q,Elevated,40.775036,-73.912034,0,2,"[N, W]",2
1,10,2023-02-01 00:00:00,167.0,0.637787,49 St,M,Subway,40.759901,-73.984139,0,2,"[N, R, W]",3
2,100,2023-02-01 00:00:00,13.0,19.375850,Hewes St,Bk,Elevated,40.706870,-73.953431,0,2,"[M, J]",2
3,101,2023-02-01 00:00:00,59.0,65.802439,Marcy Av,Bk,Elevated,40.708359,-73.957757,0,2,"[M, J, Z]",3
4,118,2023-02-01 00:00:00,94.0,69.094706,3 Av,M,Subway,40.732849,-73.986122,0,2,[L],1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893771,95,2023-12-31 23:00:00,55.0,1735.530425,Gates Av,Bk,Elevated,40.689630,-73.922270,1,6,"[J, Z]",2
2893772,96,2023-12-31 23:00:00,51.0,17191.471375,Kosciuszko St,Bk,Elevated,40.693342,-73.928814,1,6,[J],1
2893773,97,2023-12-31 23:00:00,122.0,122.056086,Myrtle Av,Bk,Elevated,40.697207,-73.935657,1,6,"[M, J, Z]",3
2893774,98,2023-12-31 23:00:00,39.0,8.615516,Flushing Av,Bk,Elevated,40.700260,-73.941126,1,6,"[M, J]",2
2893775,99,2023-12-31 23:00:00,27.0,8.807679,Lorimer St,Bk,Elevated,40.703869,-73.947408,1,6,"[M, J]",2

In [75]:
# Assuming your DataFrame is named df
merged_df['diff_23'] = merged_df['pred_23'] - merged_df['actual_23']

In [76]:
merged_df

,station_complex_id,timestamp,actual_23,pred_23,stop_name,borough,structure,lat,long,is_weekend,day_of_week,routes,num_lines_serviced,diff_23
0,1,2023-02-01 00:00:00,27.0,44.997743,Astoria-Ditmars Blvd,Q,Elevated,40.775036,-73.912034,0,2,"[N, W]",2,17.997743
1,10,2023-02-01 00:00:00,167.0,0.637787,49 St,M,Subway,40.759901,-73.984139,0,2,"[N, R, W]",3,-166.362213
2,100,2023-02-01 00:00:00,13.0,19.375850,Hewes St,Bk,Elevated,40.706870,-73.953431,0,2,"[M, J]",2,6.375850
3,101,2023-02-01 00:00:00,59.0,65.802439,Marcy Av,Bk,Elevated,40.708359,-73.957757,0,2,"[M, J, Z]",3,6.802439
4,118,2023-02-01 00:00:00,94.0,69.094706,3 Av,M,Subway,40.732849,-73.986122,0,2,[L],1,-24.905294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2893771,95,2023-12-31 23:00:00,55.0,1735.530425,Gates Av,Bk,Elevated,40.689630,-73.922270,1,6,"[J, Z]",2,1680.530425
2893772,96,2023-12-31 23:00:00,51.0,17191.471375,Kosciuszko St,Bk,Elevated,40.693342,-73.928814,1,6,[J],1,17140.471375
2893773,97,2023-12-31 23:00:00,122.0,122.056086,Myrtle Av,Bk,Elevated,40.697207,-73.935657,1,6,"[M, J, Z]",3,0.056086
2893774,98,2023-12-31 23:00:00,39.0,8.615516,Flushing Av,Bk,Elevated,40.700260,-73.941126,1,6,"[M, J]",2,-30.384484
2893775,99,2023-12-31 23:00:00,27.0,8.807679,Lorimer St,Bk,Elevated,40.703869,-73.947408,1,6,"[M, J]",2,-18.192321

In [77]:
import sys
!{sys.executable} -m pip install ipywidgets

Requirement already satisfied: ipywidgets in c:\programdata\miniconda3\lib\site-packages (8.1.5)
Requirement already satisfied: comm>=0.1.3 in c:\programdata\miniconda3\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in c:\programdata\miniconda3\lib\site-packages (from ipywidgets) (8.29.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\programdata\miniconda3\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\programdata\miniconda3\lib\site-packages (from ipywidgets) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in c:\programdata\miniconda3\lib\site-packages (from ipywidgets) (3.0.13)
Requirement already satisfied: decorator in c:\programdata\miniconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\miniconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\programdata\miniconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\programdata\miniconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.48)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\miniconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)
Requirement already satisfied: stack-data in c:\programdata\miniconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: colorama in c:\programdata\miniconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\programdata\miniconda3\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: wcwidth in c:\programdata\miniconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in c:\programdata\miniconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\programdata\miniconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in c:\programdata\miniconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: six>=1.12.0 in c:\programdata\miniconda3\lib\site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)

In [78]:
import plotly.graph_objects as go
import plotly.express as px
import ipywidgets as widgets
from ipywidgets import interactive

In [79]:
def plot_station(station_complex_id):
    station_data = merged_df[merged_df['station_complex_id'] == station_complex_id]

    # Time series plot for predicted vs actual
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=station_data['timestamp'], y=station_data['pred_23'], mode='lines', name='Predicted Ridership'))
    fig.add_trace(go.Scatter(x=station_data['timestamp'], y=station_data['actual_23'], mode='lines', name='Actual Ridership'))
    fig.update_layout(title=f"Predicted vs Actual Ridership - {station_complex_id}", xaxis_title="Date", yaxis_title="Ridership")
    
    fig_diff = go.Figure()
    fig_diff.add_trace(go.Scatter(x=station_data['timestamp'], y=station_data['diff_23'], mode='lines', name='Difference (Pred - Actual)', line=dict(color='green' if station_data['diff_23'].iloc[0] > 0 else 'red')))
    fig_diff.update_layout(title=f"Difference in Ridership - {station_complex_id}", xaxis_title="Date", yaxis_title="Difference")
    
    fig.show()
    fig_diff.show()

# Dropdown for station selection
station_dropdown = widgets.Dropdown(
    options=merged_df['station_complex_id'].unique(),
    description='Station:',
)

interactive(plot_station, station_complex_id=station_dropdown)

interactive(children=(Dropdown(description='Station:', options=('1', '10', '100', '101', '118', '119', '120', …

In [80]:
!{sys.executable} -m pip install bokeh

Requirement already satisfied: bokeh in c:\programdata\miniconda3\lib\site-packages (3.6.1)
Requirement already satisfied: Jinja2>=2.9 in c:\programdata\miniconda3\lib\site-packages (from bokeh) (3.1.4)
Requirement already satisfied: contourpy>=1.2 in c:\users\one1c\appdata\roaming\python\python312\site-packages (from bokeh) (1.3.0)
Requirement already satisfied: numpy>=1.16 in c:\programdata\miniconda3\lib\site-packages (from bokeh) (2.0.2)
Requirement already satisfied: packaging>=16.8 in c:\programdata\miniconda3\lib\site-packages (from bokeh) (24.1)
Requirement already satisfied: pandas>=1.2 in c:\programdata\miniconda3\lib\site-packages (from bokeh) (2.2.3)
Requirement already satisfied: pillow>=7.1.0 in c:\users\one1c\appdata\roaming\python\python312\site-packages (from bokeh) (11.0.0)
Requirement already satisfied: PyYAML>=3.10 in c:\programdata\miniconda3\lib\site-packages (from bokeh) (6.0.2)
Requirement already satisfied: tornado>=6.2 in c:\programdata\miniconda3\lib\site-packages (from bokeh) (6.4.1)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\programdata\miniconda3\lib\site-packages (from bokeh) (2024.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\miniconda3\lib\site-packages (from Jinja2>=2.9->bokeh) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\miniconda3\lib\site-packages (from pandas>=1.2->bokeh) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\miniconda3\lib\site-packages (from pandas>=1.2->bokeh) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\miniconda3\lib\site-packages (from pandas>=1.2->bokeh) (2024.2)
Requirement already satisfied: six>=1.5 in c:\programdata\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.2->bokeh) (1.16.0)

In [81]:
from bokeh.plotting import figure, show, output_notebook
from bokeh.io import push_notebook
from bokeh.models import ColumnDataSource, Select
from bokeh.layouts import column

In [82]:
# Prepare for interactivity
output_notebook()

def update_plot(attr, old, new):
    station_data = merged_df[merged_df['station_complex_id'] == new]
    source.data = station_data

    # Update the plots
    p1.line(station_data['timestamp'], station_data['pred_23'], legend_label="Predicted Ridership", color="blue", line_width=2)
    p1.line(station_data['timestamp'], station_data['actual_23'], legend_label="Actual Ridership", color="red", line_width=2)
    
    diff_23 = station_data['pred_23'] - station_data['actual_23']
    p2.line(station_data['timestamp'], diff_23, legend_label="Difference", color="green", line_width=2)

# Create a ColumnDataSource from the initial data
source = ColumnDataSource(merged_df)

# Create the figure
p1 = figure(x_axis_type="datetime", title="Predicted vs Actual Ridership")
p1.xaxis.axis_label = "Date"
p1.yaxis.axis_label = "Ridership"

p2 = figure(x_axis_type="datetime", title="Difference in Ridership")
p2.xaxis.axis_label = "Date"
p2.yaxis.axis_label = "Difference"

# Dropdown for selecting the subway station
select = Select(title="Station:", value="A", options=merged_df['station_complex_id'].unique().tolist())
select.on_change('value', update_plot)

layout = column(select, p1, p2)
show(layout, notebook_handle=True)

KeyboardInterrupt:

In [ ]:
!{sys.executable} -m pip install altair

In [ ]:
import altair as alt

In [ ]:
# Create the base chart
base = alt.Chart(merged_df).encode(x='timestamp:T')

# Create the predicted vs actual plot
line_pred_actual = base.mark_line().encode(
    y='pred_23:Q', color=alt.value('blue')
).properties(title='Predicted vs Actual Ridership')

# Create the difference plot
line_diff = base.mark_line().encode(
    y='diff_23:Q', color=alt.condition('datum.diff_23 > 0', alt.value('green'), alt.value('red'))
).properties(title='Difference in Ridership')

line_pred_actual | line_diff  # Combine both plots vertically